---
title: "cs_dat"
author: "Nigus and Eskedar"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import the data
```{r}

 dat_cs <- read_sav("thesis_data_NB.sav")

```

## explore the data
```{r}
str(dat_cs)
```

## filter the data
```{r}
new_data <- dat_cs %>% 
  select(participant_id, gravidity, parity, abortion, IUFD, Preterm_d, instrumental_d, C_S, ANC, mode_delivery_last, DM, PROM, dat_cs$PTL, dat_cs$APH, HDP, mode_delivery)
```

## explore the new data
```{r}
colSums(is.na(new_data))
str(new_data)
```

## recode variables
```{r}
## outcome
new_data <- mutate(new_data, outcome= ifelse(as.character(new_data$mode_delivery) == "5", 1, 0))

## Abortion
new_data$abortion <-ifelse(as.character(new_data$abortion) == "1", 1, 0)

## IUFD
new_data$IUFD <-ifelse(as.character(new_data$IUFD) == "1", 1, 0)

## PRETERM
new_data$Preterm_d <-ifelse(as.character(new_data$Preterm_d) == "1", 1, 0)

## inst delivery
new_data$instrumental_d <-ifelse(as.character(new_data$instrumental_d) == "1", 1, 0)

## CS
new_data$C_S <-ifelse(as.character(new_data$C_S) == "1", 1, 0)

## ANC
new_data$ANC <-ifelse(as.character(new_data$ANC) == "2", 1, 0)

## previous mode del
new_data$mode_delivery_last <-ifelse(as.character(new_data$mode_delivery_last) == "2", 1, 0)

## PROM
new_data$PROM <-ifelse(as.character(new_data$PROM) == "1", 1, 0)

## HDP
new_data$HDP <-ifelse(as.character(new_data$HDP) == "1", 1, 0)
```

```{r}
full_fit <- glm(outcome~ parity +  abortion + IUFD + PROM + HDP + mode_delivery_last + ANC, family= binomial, data = new_data)

summary(full_fit)

## model reduction

stepAIC(full_fit)
```

## reduced model
```{r}
red_model <- full_fit <- glm(outcome~ IUFD  + HDP + mode_delivery_last, family= binomial, data = new_data)

hoslem.test(red_model$fitted.values, red_model$y, g=10)

```

## model performance
```{r}
prediction_cs <- predict(red_model, type = "response")

plotCalibration(data = new_data, 16, predRisk = prediction_cs)


plot.roc(new_data$outcome, prediction_cs, print.auc= T, ci= T)
```


```{r}
## LASSO regression

# Extract response variable 'outcome'
y <- new_data$outcome

# Select predictor variables
x <- model.matrix(outcome ~ parity + abortion + IUFD + PROM + HDP + mode_delivery_last + ANC, data = new_data)[,-1]

set.seed(123)  # for reproducibility
cv_fit <- cv.glmnet(x, y, family = "binomial")

print(cv_fit$lambda.min)

# Predict using the fitted model
predictions <- predict(cv_fit, newx = x, s = "lambda.min", type = "response")

# Get coefficients at the lambda that gives minimum mean cross-validated error
lasso_coefficients <- coef(cv_fit, s = "lambda.min")

# Print the coefficients
print(lasso_coefficients)


```
```{r}
lasso_model <- glm(outcome ~ parity + HDP + mode_delivery_last + ANC, family = binomial, data = new_data)

hoslem.test(lasso_model$fitted.values, lasso_model$y, g=2)
```

