---
title: "risk of CS among multi-parous women"
author: "Eskedar and Nigus"
date: "2023-12-09"
output: html_document
---


```{r}
setwd("C:/Users/User/Desktop/Nigus")
```
##Load important pakage 
```{r}
library(PredictABEL)
library(pROC)
library(readxl)
library(haven)
library(boot)
library(ggplot2)
library(tidyverse)
library(MASS)
```

## import the data
```{r}
dat_cs <- read_sav("thesis_data_NB.sav")
```

## explore the data
```{r}
str(dat_cs)
dat_cs <- dat_cs[-310, ]
```

## filter the data
```{r}
new_data <- dat_cs %>% 
  dplyr::select(participant_id, age, gravidity, parity, abortion, IUFD, Preterm_d, instrumental_d, C_S, ANC, mode_delivery_last, DM, PROM, PTL, APH, HDP, mode_delivery,medical_illness,number_ANC_cat)
```

## explore the new data
```{r}
colSums(is.na(new_data))
str(new_data)
```

## recode variables
```{r}
## outcome
new_data <- mutate(new_data, outcome= ifelse(as.character(new_data$mode_delivery) == "5", 1, 0))
##Advanced age
new_data<-mutate(new_data, Advanced_age=ifelse(age>34,1,0))
##history of any medical illness 
new_data$medical_illness<-ifelse(as.character(new_data$medical_illness)=="1", 1, 0)
##ANC visit
new_data$number_ANC_cat<-ifelse(as.character(new_data$number_ANC_cat)=="1", 1, 0)
## Abortion
new_data$abortion <-ifelse(as.character(new_data$abortion) == "1", 1, 0)

## IUFD
new_data$IUFD <-ifelse(as.character(new_data$IUFD) == "1", 1, 0)

## PRETERM
new_data$Preterm_d <-ifelse(as.character(new_data$Preterm_d) == "1", 1, 0)

## inst delivery
new_data$instrumental_d <-ifelse(as.character(new_data$instrumental_d) == "1", 1, 0)

## CS
new_data$C_S <-ifelse(as.character(new_data$C_S) == "1", 1, 0)

## ANC
new_data$ANC <-ifelse(as.character(new_data$ANC) == "2", 1, 0)

## previous mode del
new_data$mode_delivery_last <-ifelse(as.character(new_data$mode_delivery_last) == "2", 1, 0)

## PROM
new_data$PROM <-ifelse(as.character(new_data$PROM) == "1", 1, 0)

## HDP
new_data$HDP <-ifelse(as.character(new_data$HDP) == "1", 1, 0)
##categorize age 
new_data <- mutate(new_data, Age_cat= ifelse(new_data$age <20,1,ifelse(new_data$age >34,2,0)))
```
 
```{r}
full_fit <- glm(outcome~ parity +  abortion + PROM + HDP + mode_delivery_last + ANC+Advanced_age+number_ANC_cat+medical_illness, family= binomial, data = new_data)

summary(full_fit)

## model reduction

stepAIC(full_fit)
```

## reduced model
```{r}
red_model <- full_fit <- glm(outcome~  HDP + mode_delivery_last, family= binomial, data = new_data)
```

## model performance/calibration 
```{r}
predicted_probabilities <- predict(red_model, type = "response")
calibration_data <- data.frame(Outcome = new_data$outcome, Predicted_Risks = predicted_probabilities)
predRisk <- predRisk(red_model)
plotCalibration(calibration_data, 1, predRisk, 10,plottitle = "Calibration_of_the_model")
```
###Calibration plot
```{r}
predsred = predict(red_model,type="response")
plot.roc(new_data$outcome, predsred,print.auc=TRUE)
```
##Model development using Least square absolute shrinkage operator 
```{r}
## LASSO regression

# Extract response variable 'outcome'
y <- new_data$outcome

# Select predictor variables
x <- model.matrix(outcome ~ parity + abortion + IUFD + PROM + HDP + mode_delivery_last + ANC, data = new_data)[,-1]

set.seed(123)  # for reproducibility
cv_fit <- cv.glmnet(x, y, family = "binomial")

print(cv_fit$lambda.min)

# Predict using the fitted model
predictions <- predict(cv_fit, newx = x, s = "lambda.min", type = "response")

# Get coefficients at the lambda that gives minimum mean cross-validated error
lasso_coefficients <- coef(cv_fit, s = "lambda.min")

# Print the coefficients
print(lasso_coefficients)
```

## Risk_score calculation 
```{r}
new_data$HDP_rs<-as.numeric(new_data$HDP)
new_data$mode_delivery_last_rs<-as.numeric(new_data$mode_delivery_last)
new_data$Risk_score<-(1*new_data$HDP_rs)+(3*new_data$mode_delivery_last_rs)
cor.test(new_data$outcome,new_data$Risk_score)
```

##model with the risk score 
```{r}
risk<-glm(new_data$outcome~new_data$Risk_score,family = binomial)
predsrisk = predict(risk,type="response")
plot.roc(new_data$outcome, predsrisk,print.auc=TRUE)
```
```{r}
library(dcurves)
library(rmda)
Dcred<-decision_curve(outcome~  HDP + mode_delivery_last, family= binomial, data = new_data,thresholds = seq(0, 1, by = .01),confidence.intervals = 0.95) 
# Define the colors for each line
line.colors <- c("blue", "green","red")
plot_decision_curve(x=Dcred, curve.names=c("Model", "Intervention for all", "Intervention for none"), cost.benefit.axis = TRUE,col = line.colors)
```

